/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sudoku;

/**
 *
 * @author abdallah
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_startgame = new javax.swing.JButton();
        Toogle_Easy = new javax.swing.JToggleButton();
        Toogle_Hard = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 5, 6));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_startgame.setBackground(new java.awt.Color(0, 0, 0));
        btn_startgame.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        btn_startgame.setForeground(new java.awt.Color(255, 255, 255));
        btn_startgame.setText("Start Game");
        btn_startgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startgameActionPerformed(evt);
            }
        });
        jPanel1.add(btn_startgame, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 35, 110, 33));

        Toogle_Easy.setBackground(new java.awt.Color(0, 0, 0));
        Toogle_Easy.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Toogle_Easy.setForeground(new java.awt.Color(255, 255, 255));
        Toogle_Easy.setText("Easy");
        jPanel1.add(Toogle_Easy, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 110, 33));

        Toogle_Hard.setBackground(new java.awt.Color(0, 0, 0));
        Toogle_Hard.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Toogle_Hard.setForeground(new java.awt.Color(255, 255, 255));
        Toogle_Hard.setText("Hard");
        jPanel1.add(Toogle_Hard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, 33));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/abdallah/Desktop/Sudoku/Project Pic/choose-level.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/abdallah/Desktop/Sudoku/Project Pic/bg.jpg")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 350, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 190, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/abdallah/Desktop/Sudoku/Project Pic/bg-mainMenu.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startgameActionPerformed
        
    }//GEN-LAST:event_btn_startgameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Toogle_Easy;
    private javax.swing.JToggleButton Toogle_Hard;
    private javax.swing.JButton btn_startgame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
